### ISSUE TITLE
import google

### ISSUE THREAD

**Issue by texereda** [opsdisk/theHarvester#3]
Hi there,

I think that in theHarvester.py the following line:
`import google  # https://pypi.python.org/pypi/google`

should be removed, since a few lines below you have:

`import googlesearch`

otherwise error is returned:
Traceback (most recent call last):
  File "theHarvester.py", line 3, in <module>
    import google  # https://pypi.python.org/pypi/google
ImportError: No module named google

Thank you and please excuse me if I'm not submitting a pull request, I'm still learning GIT :-)

**Comment by opsdisk** [comment]
Hey @texereda thanks for the issue submission!  This is an easy enough fix that would be a gentle introduction into pull requests for you if you wanted the practice.  This should help you get started https://help.github.com/articles/creating-a-pull-request-from-a-fork/  Looking forward to your PR!

**Comment by opsdisk** [comment]
Updated script in...let me know if you find any bugs!
